server:
  port: 8081

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      # 数据源1
      first:
        url: jdbc:mysql://39.96.178.201:3306/practice_springboot?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456

      # 数据源2
      second:
        url: jdbc:mysql://101.37.12.126:3306/test?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456


#annotation:
#  jdbc:
#    default-data-source:
#      name: "default"
#      base-url: "jdbc:mysql://39.96.178.201:3306"
#      db: "practice_springboot"
#      search-url: "serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf8"
#      driver-class-name: "com.mysql.cj.jdbc.Driver"
#      username: "root"
#      password: "123456"
#mybatis:
#  mapper-locations: "classpath:mapper/*.xml"
#  type-aliases-package: com.tt.spring.annotation.test.pojo.dto
